version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: deviceatlas-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/deviceatlas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=deviceAtlas
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ../deviceatlas-frontend
      dockerfile: Dockerfile
    container_name: deviceatlas-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: deviceatlas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deviceAtlas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
